author: "Nikolas Siccha"
project:
  type: website
website:
  title: "NUTS.jl"
  navbar:
    search: true
    left:
      - icon: github
        href:  https://github.com/nsiccha/NUTS.jl
format: 
    html:
        page-layout: full
        toc: true
        code-line-numbers: true
        code-tools: true
jupyter: julia-1.10
execute:
  echo: false
  cache: true
  daemon: 60000